# SMILES → fingerprints ECFP4 en format per ser input de MolForge
Transforma una taula amb **SMILES** en **fingerprints** amb el format necessati per fer-se servir com a input de MolForge.

**Entrada**: CSV amb columna `in_col_name`.

**Sortida**: CSV amb columnes `in_col_name` i `out_col_name_ECFP4`.

## Imports

In [1]:
# Per definir l'arrel del projecte
import os

# Pandas pels dataframes
import pandas as pd

# Per no mostrar els Warnings de RDKit
from rdkit import RDLogger
RDLogger.DisableLog("rdApp.*")

## Inputs (part a editar)

Arrel del projecte

In [2]:
#os.chdir("/export/home/ddiestre/MolForge_Testing")
#os.chdir("/mnt/c/Users/david/Desktop/Uni/MolForge_Testing")
os.chdir("/mnt/d/MolForge_Testing")

In [3]:
# Importem la funció smiles_to_fingerprint del nostre sourcecode que utilitza RDKit
from src.smiles_to_fp import smiles_to_fingerprint

Fingerprints en que transformar els SMILES

In [4]:
fp_type = "ECFP4"

Fitxer de fingerprints preprocessat (path a partir de MolForge_Testing/)

In [5]:
#input_path = "data/SMILES/MolForge_2000_ECFP4.csv"
#input_path = "data/SMILES/CoCoGraph_2000_novel.csv"
#input_path = "data/SMILES/CoCoGraph_2000_lt70atoms.csv"
input_path = "data/SMILES/PubChem_2000_CID-SMILES-filtered-lt70.csv"

in_col_name = "SMILES_input"

Fitxer en que guardar l'output (path a partir de MolForge_Testing/)

In [6]:
#output_path = "data/MolForge_input/MolForge_MFinput_2000_ECFP4.csv"
#output_path = "data/MolForge_input/CoCoGraph_MFinput_2000_novel.csv"
#output_path = "data/MolForge_input/CoCoGraph_MFinput_2000_lt70atoms.csv"
output_path = "data/MolForge_input/PubChem_MFinput_2000_CID-SMILES-filtered-lt70.csv"

out_col_name = "fingerprints_input_" + fp_type

## 1. Lectura del fitxer

In [7]:
# Lectura del fitxer
df = pd.read_csv(input_path, sep = ',', index_col = 0)
df.head(5)

                                         SMILES_input
id
1     CCCC1=NN=C(C=C1)C2CCC(CC2)C(C=O)C3CCC(CC3)CCCCl
2   CC1=C(C(OC2=C1C=C(C=C2)O)C3=CC=C(C=C3)OC[C@H](...
3                              CC(C)C1CCNC(=O)C1C(C)C
4   CSC1=NN(C=C1/C(=N\OC(=O)NC2=CC=CC=C2)/N)C3=CC=...
5              CCC1=C(C(=NC(=N1)CC2=CC=CC=C2Br)CC)CCN

## 2. Columna SMILES → Columna de fingerprints

In [8]:
fingerprints = []

# Apliquem el conversor SMILES -> fingerprint
fingerprints = df[in_col_name].apply(
    lambda s: smiles_to_fingerprint(s, fp_type=fp_type, n_bits=2048, return_bits=True)
)

# Guardem les fingerprints en el mateix format que l'input de MolForge
df[out_col_name] = fingerprints.apply(
    lambda lst: " ".join(str(x) for x in lst) if isinstance(lst, list) else lst
)

## 3. Guardar l'output

In [9]:
# Visualitzem el nou dataframe
df.head(5)

,SMILES_input,fingerprints_input_ECFP4
id,,
1,CCCC1=NN=C(C=C1)C2CCC(CC2)C(C=O)C3CCC(CC3)CCCCl,1 29 80 114 160 294 378 380 472 508 650 694 71...
2,CC1=C(C(OC2=C1C=C(C=C2)O)C3=CC=C(C=C3)OC[C@H](...,1 29 34 38 80 102 118 245 249 283 305 322 352 ...
3,CC(C)C1CCNC(=O)C1C(C)C,1 81 208 253 283 305 314 650 707 764 926 1019 ...
4,CSC1=NN(C=C1/C(=N\OC(=O)NC2=CC=CC=C2)/N)C3=CC=...,32 61 116 140 177 191 378 389 394 431 464 591 ...
5,CCC1=C(C(=NC(=N1)CC2=CC=CC=C2Br)CC)CCN,57 80 129 294 378 394 398 728 833 858 883 892 ...

In [10]:
df.to_csv(output_path)